import { init } from './scripts/sticky-menu';
import { mobileMenu, statsDrawer } from './scripts/mobile-menu';
import { ritualAnimation } from './scripts/summon-ritual';
import { initLandSlider } from './scripts/land-slider';
import { ritualSections } from './scripts/ritual-sections';
import { initMandalas } from './scripts/mandalas';
import { wizardSlider } from './scripts/wizard-slider';
import { initLetsPlay } from './scripts/lets-play';
import { initDeviceDetection } from './scripts/device-detection';
window.Webflow ||= [];
window.Webflow.push(() => {
  init();
  mobileMenu();
  statsDrawer();
  ritualAnimation();
  ritualSections();
  initLandSlider();
  initMandalas();
  wizardSlider();
  initLetsPlay();
  initDeviceDetection();
});
